In [12]:
import yfinance as yf
import pandas as pd 
from pandas.tseries.offsets import MonthEnd

In [13]:
# URL for the regularly updated Wikipedia page containing the current S&P 500 constituents
url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies#S&P_500_component_stocks"
tickers = pd.read_html(url, storage_options={"User-Agent": "Mozilla/5.0"})[0].Symbol

In [14]:
# URL for the Wikipedia page containing historical S&P 500 additions and removals
url_changes = "https://en.wikipedia.org/wiki/Historical_components_of_the_S&P_500"
changes = pd.read_html(url_changes, storage_options={"User-Agent": "Mozilla/5.0"})[0]

In [15]:
# Convert the Effective Date column to datetime format
changes[("Effective Date")] = pd.to_datetime(changes[("Effective Date", "Effective Date")])

In [16]:
# Remove changes that occurred before 2024
changes = changes[changes[("Effective Date", "Effective Date")] >= "2024-01-01"]

In [17]:
# Remove stocks that were added to the S&P 500 from 2024 onwards
tickers = tickers[~(tickers.isin(changes.Added.Ticker))]

In [18]:
# Get the tickers of stocks that were removed from the S&P 500 from 2024 onwards
tickers_rem = changes.Removed.Ticker

In [19]:
# Add stocks removed since 2024 to the current list of S&P 500 tickers
tickers = pd.concat([tickers, tickers_rem])

In [20]:
# Remove duplicate tickers and missing values
tickers.drop_duplicates(inplace=True)
tickers.dropna(inplace=True)

In [ ]:
#Variable to set the start date of the DataFrame
start = "2024-01-01"

In [ ]:
#empty lists to store price and symbols
prices, symbols = [], []

#Stores price data in prices list
for symbol in tickers:
    df = yf.download(symbol, start=start)["Close"]
    if not df.empty:
        prices.append(df)
        symbols.append(symbol)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
$BRK.B: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BRK.B']: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
$BF.B: possibly delisted; no price data found  (1d 2024-01-01 -> 2026-08-24)
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['BF.B']: possibly delisted; no price data found  (1d 2024-01-01 -> 2026-08-24)
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [ ]:
#Stores Prices in a DataFrame
all_prices = pd.concat(prices, axis=1)

In [ ]:
all_prices

Ticker,MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,...,BBWI,AAL,ETSY,BIO,RHI,ILMN,XRAY,VFC,WHR,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2024-01-02,86.408249,77.233475,103.769409,145.533875,329.828705,580.070007,138.580002,16.883278,78.544304,136.120483,...,41.190311,13.44,81.080002,327.989990,75.034508,133.861862,33.107227,17.657448,106.673775,40.303596
2024-01-03,84.672218,74.644485,103.457703,146.116684,321.272095,571.789978,135.320007,16.525360,78.459419,128.674332,...,40.122574,12.95,79.129997,318.859985,73.143608,126.789886,32.354576,16.578121,102.307869,38.349594
2024-01-04,84.970741,75.279877,104.836876,147.027298,320.482941,567.049988,136.009995,16.472980,77.620041,128.517395,...,39.984516,13.09,76.290001,316.480011,72.411659,127.850197,33.153687,16.038454,102.559593,38.933975
2024-01-05,85.300636,74.957451,104.666855,147.646484,320.036133,564.599976,138.580002,16.411875,78.016144,128.085724,...,41.153492,13.60,75.639999,316.380005,72.237389,126.926071,32.874924,16.000586,104.981224,40.221424
2024-01-08,85.512749,75.175560,106.178276,146.999954,323.582397,580.549988,146.179993,16.647575,78.157616,130.852280,...,42.018715,14.58,77.760002,321.980011,72.542366,130.019455,33.358109,16.407701,105.840530,40.668835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-17,180.210007,61.400002,110.370003,250.330002,169.979996,254.039993,506.000000,14.760000,120.373764,148.449997,...,18.618452,14.43,78.410004,355.230011,42.470001,193.139999,11.190000,14.480000,39.590000,71.580002
2026-08-18,180.940002,60.860001,112.680000,258.920013,172.929993,263.140015,484.390015,14.740000,121.120003,148.440002,...,19.835928,14.05,79.959999,352.690002,43.759998,188.289993,11.110000,14.310000,39.270000,70.930000
2026-08-19,180.660004,63.799999,114.430000,265.970001,183.169998,272.470001,466.420013,14.700000,116.510002,155.410004,...,19.469694,13.86,80.459999,364.260010,43.540001,205.000000,11.030000,14.370000,40.090000,68.290001
2026-08-20,178.089996,62.430000,114.139999,261.829987,181.350006,272.220001,469.459991,14.770000,116.169998,156.300003,...,19.440001,13.52,81.209999,376.459991,43.880001,213.240005,10.780000,13.950000,40.470001,67.889999
2026-08-21,178.960007,63.080002,116.639999,264.959991,185.279999,275.299988,473.250000,14.770000,116.070000,159.000000,...,19.450001,13.82,81.029999,380.029999,44.750000,219.399994,10.920000,14.370000,40.349998,68.139999

In [ ]:
#Calculates monthly returns via grouping daily returns into respective month-ends 
all_mtl_rtn = all_prices.pct_change(fill_method=None).resample("ME").agg(lambda x: (x + 1).prod() - 1)

In [43]:
all_mtl_rtn

Ticker,MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,...,BBWI,AAL,ETSY,BIO,RHI,ILMN,XRAY,VFC,WHR,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2024-01-31,-0.142273,-0.043279,0.035017,0.038485,0.052718,0.065009,0.210059,-0.128656,0.012728,-0.062342,...,-0.046704,0.058780,-0.179082,-0.021647,-0.076298,0.039241,-0.024698,-0.117426,-0.108869,-0.050747
2024-02-29,-0.007418,0.068161,0.048519,0.070864,0.029955,-0.093075,0.148130,-0.088729,-0.036616,0.055803,...,0.075897,0.101897,0.077073,0.015550,0.017554,-0.022236,-0.059568,-0.007290,-0.003242,-0.049039
2024-03-31,0.151433,0.079131,-0.041976,0.034365,-0.075164,-0.099379,-0.062536,0.179606,0.063413,0.059333,...,0.094530,-0.021046,-0.041428,0.061342,-0.013931,-0.017950,0.020631,-0.055919,0.113977,0.100685
2024-04-30,0.088205,-0.070425,-0.063034,-0.098523,-0.128487,-0.082778,-0.122500,0.008091,-0.025739,-0.056679,...,-0.091963,-0.119870,-0.000728,-0.220083,-0.127901,-0.103918,-0.095812,-0.187744,-0.207055,-0.060369
2024-05-31,0.044819,0.009657,-0.035670,-0.008608,-0.061879,-0.039042,0.053795,0.206145,0.080518,-0.048380,...,0.143549,-0.148779,-0.075724,0.063429,-0.063653,-0.152540,-0.066644,0.065811,-0.000875,0.068935
2024-06-30,0.020471,-0.022238,0.016831,0.063756,0.074817,0.249078,-0.028101,-0.186197,-0.006231,-0.005981,...,-0.244914,-0.014783,-0.070742,-0.047933,-0.003892,0.028986,-0.105013,0.023348,0.098570,0.004168
2024-07-31,0.248165,0.043772,0.024945,0.090382,0.094460,-0.007002,-0.109303,0.012521,0.067966,0.092821,...,-0.058899,-0.060900,0.104442,0.238915,0.003282,0.174555,0.089522,0.256296,-0.002250,0.191376
2024-08-31,0.061671,-0.015522,0.069190,0.059303,0.034269,0.041258,0.028239,-0.027644,0.162603,0.010750,...,-0.158046,-0.001880,-0.154283,-0.003074,-0.015277,0.071778,-0.068165,0.073703,0.000612,-0.032085
2024-09-30,0.014923,0.072981,0.006533,0.005960,0.033718,-0.098588,0.104470,0.171045,0.013048,0.038903,...,0.037711,0.058380,0.007987,-0.008123,0.075634,-0.007534,0.076485,0.101189,0.066906,-0.047216
2024-10-31,-0.060205,-0.160215,-0.000927,0.040602,-0.020529,-0.076674,-0.121953,-0.177966,-0.062701,-0.120976,...,-0.110902,0.192171,-0.073654,0.070566,0.010384,0.105283,-0.143755,0.038095,-0.032617,0.102499
2024-11-30,0.044914,-0.008123,0.047632,-0.102713,0.050896,0.079171,-0.047824,-0.200833,0.092807,0.058783,...,0.285316,0.083582,0.066485,-0.049303,0.103268,0.000069,-0.151921,-0.023177,0.093195,0.170867
2024-12-31,-0.033251,-0.084307,-0.047655,-0.028590,-0.029197,-0.138100,-0.119478,-0.013037,-0.092632,-0.024511,...,0.069812,0.200413,-0.035910,-0.035298,-0.055623,-0.072979,-0.025963,0.065293,0.027464,-0.103602
2025-01-31,0.179022,-0.008332,0.136958,0.044649,0.098911,-0.016259,-0.040070,-0.131740,0.038090,0.127885,...,-0.029920,-0.029260,0.038192,0.098536,-0.080471,-0.006660,0.041096,0.210159,-0.082722,0.066544
2025-02-28,0.024213,-0.012184,0.078793,0.136650,-0.094688,0.002537,-0.138767,0.053636,0.025167,-0.155755,...,-0.031893,-0.151891,-0.067747,-0.265241,-0.078993,-0.331475,-0.162449,-0.040046,-0.013858,-0.058725
2025-03-31,-0.053249,-0.016847,-0.038838,0.002344,-0.104620,-0.125479,0.028840,0.071613,0.015712,-0.085522,...,-0.163125,-0.264808,-0.078336,-0.081460,-0.076832,-0.105927,-0.087951,-0.374514,-0.114550,-0.077350
2025-04-30,-0.054133,0.043544,-0.009757,-0.060219,-0.036555,-0.022293,-0.052463,-0.194847,-0.022574,-0.078231,...,0.006266,-0.056872,-0.078423,0.002135,-0.187901,-0.021931,-0.069612,-0.234536,-0.153667,-0.098075
2025-05-31,0.073188,-0.052314,0.021644,-0.046079,0.059067,0.106966,0.137442,0.027077,-0.042034,0.040149,...,-0.078335,0.146734,0.272999,-0.070264,0.047032,0.059794,0.149640,0.048822,0.045608,0.062366
2025-06-30,0.026222,0.019593,0.018191,-0.002633,-0.056594,-0.067961,0.281495,0.042616,0.018544,0.054414,...,0.073508,-0.016652,-0.093767,0.063412,-0.103516,0.160141,0.003780,-0.050418,0.298758,0.096706
2025-07-31,-0.019837,0.084817,-0.068036,0.027112,-0.101891,-0.075450,0.242495,0.250000,-0.057842,-0.025067,...,-0.033378,0.024064,0.161683,0.002611,-0.100853,0.076512,-0.098867,-0.002553,-0.181227,0.032345
2025-08-31,0.047102,0.007063,0.051272,0.113110,-0.026694,-0.002768,-0.077591,0.043626,0.081351,0.094504,...,0.015536,0.163621,-0.090269,0.231163,0.027080,-0.026774,-0.000699,0.290956,0.132539,0.090988
2025-09-30,-0.002250,0.029738,0.009649,0.100475,-0.051429,-0.011074,-0.005165,-0.028065,0.045293,0.023458,...,-0.118110,-0.159312,0.252405,-0.058715,-0.089496,-0.049920,-0.100959,-0.040600,-0.156200,-0.024651
2025-10-31,0.072948,-0.096198,-0.072945,-0.051516,0.014193,-0.035266,0.583040,0.067350,-0.040376,0.140319,...,-0.049689,0.168150,-0.066124,0.139663,-0.229252,0.300832,-0.006304,-0.027027,-0.088677,-0.079003
2025-11-30,0.037774,-0.000151,0.042711,0.044304,-0.000400,-0.059299,-0.150672,0.013699,0.034476,0.048784,...,-0.279701,0.070069,-0.125484,0.016617,0.055236,0.064028,-0.100714,0.246439,0.093869,0.030333
2025-12-31,-0.069457,0.013640,-0.028006,0.003470,0.073200,0.093275,-0.015492,0.019915,-0.000363,-0.113551,...,0.153360,0.091103,0.022501,-0.067321,0.004438,-0.002206,0.022518,0.038286,-0.067356,0.099756
2026-01-31,-0.043348,0.104267,-0.123205,-0.016131,-0.017369,-0.162119,0.105388,0.033714,0.006167,-0.014557,...,0.085657,-0.132420,-0.044733,-0.030661,0.274300,0.104071,0.090989,0.083518,0.108816,0.023403
2026-02-28,0.084238,0.061369,0.064501,0.040671,-0.208314,-0.105166,-0.154269,0.179522,0.023254,-0.093164,...,0.052759,-0.017293,0.036254,-0.051958,-0.276332,-0.071473,0.177225,-0.008678,-0.133234,-0.037011
2026-03-31,-0.121522,-0.154615,-0.117576,-0.062866,-0.049971,-0.073663,0.016083,-0.184607,-0.028513,-0.058823,...,-0.179701,-0.178271,-0.089286,0.001113,0.040131,-0.083296,-0.209809,-0.120546,-0.212042,0.005936
2026-04-30,0.008883,-0.056846,-0.110163,-0.020308,-0.091101,0.012424,0.742565,0.025550,0.036095,0.013774,...,0.041243,0.090317,0.287315,0.004915,0.047638,0.028233,0.012931,0.114185,0.039688,0.100659
2026-05-31,0.050518,-0.082794,-0.057165,0.030286,0.046780,0.053271,0.455894,0.027743,-0.005875,0.172912,...,0.029835,0.250214,0.055642,0.115522,0.130900,0.285782,-0.108936,-0.092446,-0.225473,-0.007808
2026-06-30,0.057337,0.105783,0.060047,0.155796,-0.334794,-0.209058,0.125576,-0.000682,0.042964,-0.018037,...,0.168370,0.234290,0.109099,-0.060388,0.042799,0.078976,0.013371,-0.023939,-0.092123,0.107926
2026-07-31,0.088753,-0.035489,0.173175,0.004316,0.349366,0.221393,-0.180338,0.013375,0.087250,0.041707,...,-0.130134,-0.154953,0.084296,0.108545,0.231270,0.166468,0.260132,-0.141487,-0.048706,0.007371
2026-08-31,0.015203,0.049060,0.103500,0.055870,0.116683,0.099397,-0.006091,0.006131,-0.084919,0.149093,...,-0.023355,-0.094957,-0.007958,0.167599,0.183862,0.069722,-0.183246,0.003492,0.076000,-0.015813

In [44]:
all_mtl_rtn_12 = all_mtl_rtn.rolling(12).agg(lambda x: (x + 1).prod() - 1)

In [47]:
all_mtl_rtn_12.dropna(inplace=True)
all_mtl_rtn_12

Ticker,MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,...,BBWI,AAL,ETSY,BIO,RHI,ILMN,XRAY,VFC,WHR,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2024-12-31,0.452211,-0.148924,0.050225,0.152521,0.030339,-0.233403,-0.128374,-0.307174,0.268851,-0.025066,...,-0.115194,2.968751e-01,-0.347681,0.001585,-0.156625,-0.001732,-0.453423,0.175816,-0.003278,0.274060
2025-01-31,0.996193,-0.117836,0.153664,0.159361,0.075550,-0.291900,-0.308546,-0.309627,0.300627,0.172724,...,-0.099616,1.890373e-01,-0.175030,0.124622,-0.160436,-0.045824,-0.416551,0.612243,0.025967,0.431484
2025-02-28,1.059806,-0.184192,0.186973,0.230585,-0.054610,-0.217249,-0.481328,-0.201771,0.384038,-0.062263,...,-0.189821,-8.482142e-02,-0.285953,-0.186326,-0.240095,-0.347603,-0.480379,0.559045,0.015040,0.416905
2025-03-31,0.693649,-0.256750,0.190861,0.192489,-0.084720,-0.239933,-0.430772,-0.274849,0.321954,-0.190491,...,-0.380538,-3.127036e-01,-0.313446,-0.295805,-0.288569,-0.406048,-0.535660,0.032920,-0.193190,0.187721
2025-04-30,0.472118,-0.165626,0.258574,0.243160,0.011829,-0.189810,-0.385339,-0.420829,0.326249,-0.208985,...,-0.313526,-2.635085e-01,-0.366827,-0.095162,-0.337515,-0.351704,-0.522205,-0.026583,-0.138869,0.140060
2025-05-31,0.512089,-0.216838,0.333377,0.196173,0.142278,-0.066710,-0.336549,-0.506815,0.175826,-0.135397,...,-0.446723,-7.826100e-03,-0.127934,-0.208917,-0.259203,-0.189272,-0.411486,-0.042100,-0.098806,0.133054
2025-06-30,0.520610,-0.183333,0.335161,0.121520,0.002619,-0.303596,-0.125208,-0.368148,0.205139,-0.082866,...,-0.213405,-9.708708e-03,-0.149542,-0.116400,-0.333293,-0.085936,-0.339948,-0.111149,0.065415,0.237469
2025-07-31,0.194109,-0.151218,0.214038,0.056443,-0.177254,-0.351600,0.220307,-0.219952,0.063173,-0.181802,...,-0.192074,7.988716e-02,-0.105465,-0.284933,-0.402493,-0.162235,-0.454077,-0.294289,-0.125699,0.072285
2025-08-31,0.177723,-0.131746,0.193692,0.110105,-0.225750,-0.379015,0.094709,-0.162777,-0.011130,-0.114003,...,-0.025506,2.589454e-01,-0.037756,-0.116922,-0.376792,-0.239269,-0.414551,-0.151496,-0.010425,0.208629
2025-09-30,0.157795,-0.166739,0.197387,0.214405,-0.289525,-0.318726,-0.013957,-0.305129,0.020345,-0.127175,...,-0.171835,4.440892e-16,0.195570,-0.161964,-0.472466,-0.271758,-0.511055,-0.260749,-0.217359,0.237253
2025-10-31,0.321834,-0.103219,0.111073,0.106901,-0.264339,-0.288174,0.777747,-0.097760,0.044648,0.132278,...,-0.114817,-2.014922e-02,0.205288,-0.107876,-0.597583,-0.142917,-0.432566,-0.307124,-0.262714,0.033567
2025-11-30,0.312801,-0.096012,0.105855,0.288262,-0.300248,-0.379509,0.585727,0.144441,-0.011112,0.121585,...,-0.503938,-3.236916e-02,-0.011666,-0.046017,-0.615103,-0.088103,-0.398304,-0.115882,-0.262259,-0.090488
2025-12-31,0.263635,0.000683,0.128671,0.330778,-0.226440,-0.212940,0.772994,0.182650,0.089446,0.019210,...,-0.465198,-1.204819e-01,0.048213,-0.077684,-0.590625,-0.018484,-0.368356,-0.138296,-0.330342,0.115845
2026-01-31,0.025307,0.114305,-0.129595,0.253351,-0.308293,-0.329638,1.041656,0.408014,0.055944,-0.109507,...,-0.401480,-2.139480e-01,-0.035513,-0.186156,-0.432680,0.090930,-0.338086,-0.228472,-0.190510,0.070710
2026-02-28,0.085396,0.197277,-0.141126,0.147517,-0.395110,-0.401655,1.004907,0.576240,0.053974,-0.043487,...,-0.349146,-8.919865e-02,0.072084,0.050083,-0.554236,0.515213,-0.069641,-0.203261,-0.288501,0.095410
2026-03-31,0.007125,0.029504,-0.211485,0.072862,-0.358192,-0.366203,0.980047,0.199365,0.008082,-0.015561,...,-0.362038,1.800944e-02,0.059347,0.144482,-0.497759,0.553567,-0.193946,0.120243,-0.366840,0.194290
2026-04-30,0.074221,-0.069535,-0.291437,0.118424,-0.394528,-0.343698,2.641397,0.527671,0.068592,0.082699,...,-0.339863,1.768844e-01,0.479761,0.147656,-0.352091,0.633247,-0.122434,0.630590,-0.222186,0.457445
2026-05-31,0.051530,-0.099462,-0.346095,0.207957,-0.401553,-0.375533,3.660886,0.528662,0.108926,0.220894,...,-0.262387,2.830851e-01,0.227100,0.376989,-0.300193,0.981518,-0.319816,0.410963,-0.423840,0.361174
2026-06-30,0.083412,-0.023336,-0.319214,0.399838,-0.578029,-0.470068,3.093798,0.465179,0.135513,0.137004,...,-0.197207,6.105169e-01,0.501794,0.216683,-0.185977,0.842889,-0.313317,0.450308,-0.597244,0.375100
2026-07-31,0.203441,-0.131648,-0.143014,0.368770,-0.366009,-0.299925,1.700641,0.187820,0.310381,0.214880,...,-0.277564,3.289818e-01,0.401750,0.345237,0.114703,0.996885,-0.039752,0.248295,-0.532057,0.341834
2026-08-31,0.166779,-0.095435,-0.100437,0.298383,-0.272616,-0.228203,1.909980,0.145145,0.108896,0.275473,...,-0.305231,3.365743e-02,0.528580,0.275782,0.284861,1.194878,-0.215165,-0.029669,-0.555418,0.210477